# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Clean the build directories"
  lane :clean do
    gradle(task: "clean")
  end

  desc "Build the app"
  lane :build do
    clean
    build_type = (options[:release] ? "Release" : "Debug")
    gradle(
      task: "assemble",
      build_type: build_type
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
